/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatclient;

import game.Message;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;

/**
 *
 * @author nurefsanalbas
 */
public class ChatScreen extends javax.swing.JFrame {

    public static int y = 0;
    public static String username;
    public static DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form ChatScreen
     */
    public ChatScreen() {
        initComponents();
        lst_ConnectedClients.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_connect = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_ConnectedClients = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btn_chatRoom = new javax.swing.JButton();
        btn_privateChatRoom = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_roomName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(155, 132, 178));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
        jLabel2.setText("Welcome to Chat Application");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 334, 29);

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username);
        txt_username.setBounds(100, 110, 90, 23);

        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 110, 63, 17);

        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        jPanel1.add(btn_connect);
        btn_connect.setBounds(220, 110, 78, 23);

        jScrollPane3.setViewportView(lst_ConnectedClients);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 200, 300, 230);

        jLabel3.setText("Connected Client List");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 147, 300, 40);

        btn_chatRoom.setText("Make Chat Room");
        btn_chatRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatRoomActionPerformed(evt);
            }
        });
        jPanel1.add(btn_chatRoom);
        btn_chatRoom.setBounds(30, 520, 170, 23);

        btn_privateChatRoom.setText("Make Private Chat Room");
        btn_privateChatRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_privateChatRoomActionPerformed(evt);
            }
        });
        jPanel1.add(btn_privateChatRoom);
        btn_privateChatRoom.setBounds(30, 490, 190, 23);

        jLabel4.setText("Room Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 460, 76, 17);

        txt_roomName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_roomNameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_roomName);
        txt_roomName.setBounds(110, 460, 110, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 592));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed

    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        username = txt_username.getText();
        Client.Start("localhost", 3000);
    }//GEN-LAST:event_btn_connectActionPerformed

    private void btn_chatRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatRoomActionPerformed

    }//GEN-LAST:event_btn_chatRoomActionPerformed

    private void btn_privateChatRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_privateChatRoomActionPerformed

        Client.pairedClient = lst_ConnectedClients.getSelectedValue();
        Message paired = (Message) new Message(Message.Message_Type.Pair);
        paired.content = Client.pairedClient;
        Client.Send(paired);
        JButton chatRoom = new JButton();
        chatRoom.setBackground(Color.pink);
        jPanel1.add(chatRoom);
        y += 50;
        chatRoom.setBounds(400, y, 150, 40);
        chatRoom.setText(txt_roomName.getText());
        Message makeRoom = (Message) new Message(Message.Message_Type.Room);
        makeRoom.content = Client.pairedClient + " " + txt_roomName.getText();
        Client.Send(makeRoom);
        String pairedCL = Client.pairedClient;
        chatRoom.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ArrayList<String> participant = new ArrayList<>();
                participant.add(Client.name);
                participant.add(pairedCL);
                ChatRoom CR= new ChatRoom(txt_roomName.getText(), participant);
                CR.setVisible(true);
            }
        });


    }//GEN-LAST:event_btn_privateChatRoomActionPerformed

    private void txt_roomNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roomNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roomNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chatRoom;
    private javax.swing.JButton btn_connect;
    private javax.swing.JButton btn_privateChatRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList<String> lst_ConnectedClients;
    public static javax.swing.JTextField txt_roomName;
    public static javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
