/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.chatclient;

import game.Message;
import javax.swing.DefaultListModel;

/**
 *
 * @author nurefsanalbas
 */
public class ChatScreen extends javax.swing.JFrame {

    public static String username;
    public static DefaultListModel<String> listModel = new DefaultListModel<>();

    /**
     * Creates new form ChatScreen
     */
    public ChatScreen() {
        initComponents();
        lst_ConnectedClients.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_connect = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_ConnectedClients = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btn_chatRoom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(155, 132, 178));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Baskerville", 1, 24)); // NOI18N
        jLabel2.setText("Welcome to Chat Application");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 334, 29);

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username);
        txt_username.setBounds(100, 110, 90, 23);

        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 110, 63, 17);

        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        jPanel1.add(btn_connect);
        btn_connect.setBounds(220, 110, 78, 23);

        jScrollPane3.setViewportView(lst_ConnectedClients);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 200, 300, 230);

        jLabel3.setText("Connected Client List");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 147, 300, 40);

        btn_chatRoom.setText("Make Chat Room");
        btn_chatRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chatRoomActionPerformed(evt);
            }
        });
        jPanel1.add(btn_chatRoom);
        btn_chatRoom.setBounds(30, 460, 170, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 647, 592));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed

    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        username = txt_username.getText();
        Client.Start("localhost", 3000);
    }//GEN-LAST:event_btn_connectActionPerformed

    private void btn_chatRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chatRoomActionPerformed
        Client.pairedClient = lst_ConnectedClients.getSelectedValue();
        Message paired = (Message) new Message(Message.Message_Type.Pair);
        paired.content = Client.pairedClient;
        Client.Send(paired);
        Client.chatRoom = new ChatRoom();
        Client.chatRoom.setVisible(true);
        
    }//GEN-LAST:event_btn_chatRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chatRoom;
    private javax.swing.JButton btn_connect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JList<String> lst_ConnectedClients;
    public static javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
